// Lanternfold as a hayao game: the pure Lights-Out logic (logic.ts) drives a
// scene-tree view of a night market strung with paper lanterns. The whole 42-level
// campaign is DATA generated by the solver-backed generator (levels.ts / campaign.ts);
// this file only VIEWS it. Art is code-as-art — radial-gradient lantern glow, soft
// shadows, a dusk-sky gradient — never a placeholder square.

import {
  Node,
  Sprite,
  Text,
  KENTO,
  mix,
  withAlpha,
  linearGradient,
  radialGradient,
  glow,
  registerNode,
  showScreen,
  hideScreen,
  audio,
  defineGame,
  type World,
} from '@hayao';
import { toggleAt, isAllLit, puzzleFromRecord } from './logic';
import { LANTERN_LEVELS } from './levels';

const W = 1280;
const H = 720;

/** Canonical, serialized game state — everything world.hash() must cover. */
interface ViewState {
  levelIndex: number;
  lit: number[];
  cursor: number;
  taps: number;
  won: boolean;
}

function initState(levelIndex: number): ViewState {
  const rec = LANTERN_LEVELS[levelIndex];
  const lit = puzzleFromRecord(rec).initial().lit;
  return { levelIndex, lit, cursor: Math.floor((rec.cols * rec.rows) / 2), taps: 0, won: false };
}

class LanternfoldView extends Node {
  override readonly type = 'LanternfoldView';
  state: ViewState = initState(0);
  private history: number[][] = [];
  private layer = new Node({ name: 'layer' });

  protected override onReady(): void {
    this.layer.cosmetic = true; // pure derived view — only `state` is canonical
    this.addChild(this.layer);
    this.rebuild();
  }

  private get rec() {
    return LANTERN_LEVELS[this.state.levelIndex];
  }

  private geom() {
    const { cols, rows } = this.rec;
    const cell = Math.min(150, Math.floor(Math.min((W - 260) / cols, (H - 260) / rows)));
    const gw = cols * cell;
    const gh = rows * cell;
    return { cols, rows, cell, ox: W / 2 - gw / 2 + cell / 2, oy: H / 2 - gh / 2 + cell / 2 + 20 };
  }

  private rebuild(): void {
    for (const c of this.layer.children.slice()) this.layer.removeChild(c);
    const { cols, rows, cell, ox, oy } = this.geom();
    const at = (i: number) => ({ x: ox + (i % cols) * cell, y: oy + Math.floor(i / cols) * cell });

    // Dusk sky: a vertical gradient panel behind everything (deep indigo → warm horizon).
    this.layer.addChild(
      new Sprite({
        name: 'sky',
        pos: { x: W / 2, y: H / 2 },
        z: -10,
        shape: { kind: 'rect', w: W, h: H },
        fill: KENTO.yohaku,
        gradient: linearGradient([KENTO.yohaku, KENTO.aiDeep, mix(KENTO.kakiDeep, KENTO.yohaku, 0.55)], 90),
      }),
    );

    // The wire the lanterns hang from, drooping slightly across the row tops.
    const wireY = oy - cell * 0.62;
    this.layer.addChild(
      new Sprite({
        name: 'wire',
        pos: { x: W / 2, y: wireY + 6 },
        z: -5,
        shape: { kind: 'rect', w: cols * cell + cell * 0.4, h: 2 },
        fill: withAlpha(KENTO.kinako, 0.5),
      }),
    );

    const lanternLit = this.state.lit;
    const litCount = lanternLit.reduce((a, b) => a + b, 0);
    for (let i = 0; i < cols * rows; i++) {
      const p = at(i);
      const lit = lanternLit[i] === 1;
      // Hanging cord from the wire to each lantern's cap.
      this.layer.addChild(
        new Sprite({ name: `cord-${i}`, pos: { x: p.x, y: (wireY + p.y - cell * 0.34) / 2 }, z: -4, shape: { kind: 'rect', w: 1.5, h: p.y - cell * 0.34 - wireY }, fill: withAlpha(KENTO.kinako, 0.4) }),
      );
      const bodyW = cell * 0.5;
      const bodyH = cell * 0.62;
      // Soft halo behind a lit lantern (radial glow), painted large and faint.
      if (lit) {
        this.layer.addChild(
          new Sprite({ name: `halo-${i}`, pos: p, z: 1, shape: { kind: 'circle', radius: cell * 0.6 }, fill: withAlpha(KENTO.kaki, 0.18), gradient: radialGradient([withAlpha(KENTO.ko, 0.5), withAlpha(KENTO.kaki, 0.0)]) }),
        );
      }
      // Top cap.
      this.layer.addChild(
        new Sprite({ name: `cap-${i}`, pos: { x: p.x, y: p.y - bodyH / 2 - 3 }, z: 3, shape: { kind: 'rect', w: bodyW * 0.5, h: 6, r: 2 }, fill: lit ? KENTO.kakiDeep : KENTO.sumiSoft }),
      );
      // Lantern body: warm vertical gradient + glow when lit; a dim paper husk when dark.
      this.layer.addChild(
        new Sprite({
          name: `lantern-${i}`,
          pos: p,
          z: 4,
          shape: { kind: 'rect', w: bodyW, h: bodyH, r: Math.min(bodyW, bodyH) * 0.42 },
          fill: lit ? KENTO.kaki : mix(KENTO.kuro, KENTO.kinako, 0.22),
          gradient: lit ? linearGradient([KENTO.ko, KENTO.kaki, KENTO.shuDeep], 90) : undefined,
          stroke: lit ? withAlpha(KENTO.gofun, 0.55) : withAlpha(KENTO.kinako, 0.4),
          strokeWidth: 2,
          shadow: lit ? glow(withAlpha(KENTO.kaki, 0.9), cell * 0.5) : undefined,
        }),
      );
      // Paper ribs — two thin lines across the body for that lantern read.
      const ribCol = lit ? withAlpha(KENTO.shuDeep, 0.5) : withAlpha(KENTO.kinako, 0.25);
      for (const ry of [-bodyH * 0.18, bodyH * 0.18]) {
        this.layer.addChild(new Sprite({ name: `rib-${i}`, pos: { x: p.x, y: p.y + ry }, z: 5, shape: { kind: 'rect', w: bodyW, h: 1.5 }, fill: ribCol }));
      }
      // Bottom tassel.
      this.layer.addChild(
        new Sprite({ name: `tassel-${i}`, pos: { x: p.x, y: p.y + bodyH / 2 + 4 }, z: 3, shape: { kind: 'rect', w: 3, h: 8, r: 1.5 }, fill: lit ? KENTO.shuDeep : KENTO.sumiSoft }),
      );
    }

    // Cursor: a bright registration ring around the selected lantern.
    const cp = at(this.state.cursor);
    this.layer.addChild(
      new Sprite({ name: 'cursor', pos: cp, z: 8, shape: { kind: 'circle', radius: cell * 0.44 }, fill: 'none', stroke: KENTO.asagi, strokeWidth: 3 }),
    );

    // HUD.
    const rec = this.rec;
    this.layer.addChild(
      new Text({ name: 'title', text: rec.actName, pos: { x: W / 2, y: 54 }, size: 30, align: 'center', fill: KENTO.gofun }),
    );
    this.layer.addChild(
      new Text({ name: 'sub', text: `Lantern ${this.state.levelIndex + 1} / ${LANTERN_LEVELS.length}   ·   ${litCount}/${lanternLit.length} lit   ·   ${this.state.taps} taps (par ${rec.depth})`, pos: { x: W / 2, y: 90 }, size: 20, align: 'center', fill: KENTO.kinako }),
    );
    this.layer.addChild(
      new Text({ name: 'hint', text: 'arrows move · Space tap · U undo · R restart', pos: { x: W / 2, y: H - 40 }, size: 18, align: 'center', fill: withAlpha(KENTO.kinako, 0.75) }),
    );
  }

  private tap(): void {
    if (this.state.won) return;
    this.history.push(this.state.lit.slice());
    this.state.lit = toggleAt(this.state.lit, this.state.cursor, this.rec.cols, this.rec.rows);
    this.state.taps++;
    audio.blip(360 + this.state.taps * 3);
    this.rebuild();
    if (isAllLit(this.state.lit)) this.win();
  }

  private moveCursor(dx: number, dy: number): void {
    if (this.state.won) return;
    const { cols, rows } = this.rec;
    let x = this.state.cursor % cols;
    let y = Math.floor(this.state.cursor / cols);
    x = Math.max(0, Math.min(cols - 1, x + dx));
    y = Math.max(0, Math.min(rows - 1, y + dy));
    const next = y * cols + x;
    if (next !== this.state.cursor) {
      this.state.cursor = next;
      audio.blip(220);
      this.rebuild();
    }
  }

  private undo(): void {
    if (this.state.won || this.history.length === 0) return;
    this.state.lit = this.history.pop()!;
    this.state.taps = Math.max(0, this.state.taps - 1);
    audio.blip(200);
    this.rebuild();
  }

  restart(): void {
    this.history = [];
    this.state = initState(this.state.levelIndex);
    hideScreen();
    this.rebuild();
  }

  gotoLevel(index: number): void {
    this.history = [];
    this.state = initState(Math.max(0, Math.min(LANTERN_LEVELS.length - 1, index)));
    hideScreen();
    this.rebuild();
  }

  private win(): void {
    this.state.won = true;
    audio.success();
    const rec = this.rec;
    const perfect = this.state.taps <= rec.depth;
    const isLast = this.state.levelIndex >= LANTERN_LEVELS.length - 1;
    showScreen({
      title: isLast ? 'The festival is lit.' : 'Lanterns lit!',
      body: perfect
        ? `Solved in ${this.state.taps} taps — the proven minimum. Flawless.`
        : `Solved in ${this.state.taps} taps (a ${rec.depth}-tap solution exists).`,
      actions: isLast
        ? [{ label: 'Walk it again', primary: true, onSelect: () => this.gotoLevel(0) }]
        : [
            { label: 'Next lantern', primary: true, onSelect: () => this.gotoLevel(this.state.levelIndex + 1) },
            { label: 'Replay', onSelect: () => this.restart() },
          ],
    });
    this.emit('solved', this.state.levelIndex);
  }

  protected override onProcess(): void {
    if (this.state.won || !this.world) return;
    const input = (this.world as World).input;
    if (input.justPressed('up')) this.moveCursor(0, -1);
    if (input.justPressed('down')) this.moveCursor(0, 1);
    if (input.justPressed('left')) this.moveCursor(-1, 0);
    if (input.justPressed('right')) this.moveCursor(1, 0);
    if (input.justPressed('confirm')) this.tap();
    if (input.justPressed('undo')) this.undo();
    if (input.justPressed('restart')) this.restart();
  }

  protected override serializeProps(): Record<string, unknown> {
    return { state: this.state };
  }
  override applyProps(props: Record<string, unknown>): void {
    if (props.state) {
      this.state = props.state as ViewState;
      this.history = [];
      this.rebuild();
    }
  }
}

registerNode('LanternfoldView', () => new LanternfoldView());

export function makeLanternfoldRoot(): LanternfoldView {
  return new LanternfoldView({ name: 'lanternfold' });
}

export const lanternfoldGame = defineGame({
  title: 'Lanternfold',
  width: W,
  height: H,
  background: KENTO.yohaku,
  build: () => makeLanternfoldRoot(),
  probe: (world) => {
    const view = world.root.find('lanternfold') as LanternfoldView | null;
    return {
      frame: world.frame,
      hash: world.hash(),
      level: view?.state.levelIndex ?? 0,
      lit: view ? view.state.lit.reduce((a, b) => a + b, 0) : 0,
      total: view ? view.state.lit.length : 0,
      taps: view?.state.taps ?? 0,
      won: view?.state.won ?? false,
    };
  },
});
