// Regenerates the outlined Hayao.js wordmark from the real Overpass 600 font,
// so the canonical lockup (see ../src/components/logo.ts) is pure vector — no
// font loading, identical everywhere. Run from web/:  node scripts/outline-logo.mjs
//
// Writes:
//   src/components/logo-wordmark.ts  — generated path constants (imported by logo.ts)
//   public/logo.svg                  — the full lockup, light-theme static colours
//   public/logo-dark.svg             — the same lockup on-dark
//
// Geometry contract (must match logo.ts):
//   - crown viewBox occupies x 2..22, cap band y 2..22 (cap height = 20 units,
//     baseline at y = 22)
//   - wordmark cap height = 20 units too (mark IS cap height — the canonical rule)
//   - gap between mark and wordmark = 0.36364 em (gap-2 at the site's 1.375rem)
import { readFileSync, writeFileSync } from 'node:fs';
import { create } from 'fontkitten';

const FONT = 'public/fonts/overpass-600.woff2';
// Kerned glyph x-positions for "Hayao.js", measured once in Chrome via SVG
// getStartPositionOfChar at font-size 2000 (= font units; Overpass upm = 2000).
// fontkitten parses glyphs but does not shape, so the browser's GPOS kerning is
// baked here. Re-measure if the font file ever changes.
const KERNED_X = [0, 1410, 2493, 3558, 4668, 5785, 6265, 6811];
const TOTAL_ADVANCE = 7780; // getComputedTextLength at the same size

const font = create(readFileSync(FONT));
if (font.unitsPerEm !== 2000 || font.capHeight !== 1400) {
  throw new Error(`font metrics changed (upm ${font.unitsPerEm}, cap ${font.capHeight}) — re-measure KERNED_X`);
}

const TEXT = 'Hayao.js';
const INK_END = 5; // glyphs [0..4] = "Hayao" (ink), [5..7] = ".js" (muted)
const S = 20 / font.capHeight; //  font units → lockup units (cap = 20)
const EM = font.unitsPerEm * S; // one em in lockup units
const GAP = (8 / 22) * EM; //      gap-2 (0.5rem) at 1.375rem, in em
const BASELINE = 22; //            the crown's foot line
const WORD_X = 22 + GAP;

const glyphs = font.glyphsForString(TEXT);
if (glyphs.length !== KERNED_X.length) throw new Error('glyph count != measured positions');

const fmt = (v) => {
  const r = Math.round(v * 100) / 100;
  return Object.is(r, -0) ? '0' : String(r);
};
function outline(indices) {
  let d = '';
  for (const i of indices) {
    const x0 = WORD_X + KERNED_X[i] * S;
    for (const { command, args } of glyphs[i].path.commands) {
      // font space is y-up around the baseline; lockup space is y-down
      const px = (k) => fmt(x0 + args[k] * S);
      const py = (k) => fmt(BASELINE - args[k] * S);
      if (command === 'moveTo') d += `M${px(0)} ${py(1)}`;
      else if (command === 'lineTo') d += `L${px(0)} ${py(1)}`;
      else if (command === 'quadraticCurveTo') d += `Q${px(0)} ${py(1)} ${px(2)} ${py(3)}`;
      else if (command === 'bezierCurveTo') d += `C${px(0)} ${py(1)} ${px(2)} ${py(3)} ${px(4)} ${py(5)}`;
      else if (command === 'closePath') d += 'Z';
      else throw new Error(`unhandled path command ${command}`);
    }
  }
  return d;
}

const HAYAO = outline([0, 1, 2, 3, 4]);
const JS = outline([5, 6, 7]);

// The lockup ink box: crown x starts at 2; glyph extremes give top/bottom.
let minY = 2; //  crown top
let maxY = 22; // crown foot
for (let i = 0; i < glyphs.length; i++) {
  const b = glyphs[i].bbox;
  minY = Math.min(minY, BASELINE - b.maxY * S);
  maxY = Math.max(maxY, BASELINE - b.minY * S);
}
const right = WORD_X + TOTAL_ADVANCE * S;
const viewBox = `2 ${fmt(minY)} ${fmt(right - 2)} ${fmt(maxY - minY)}`;

const header = `// GENERATED by web/scripts/outline-logo.mjs — do not edit by hand.
// The "Hayao.js" wordmark outlined from Overpass 600 (public/fonts/overpass-600.woff2)
// with browser-measured kerning, in lockup units (crown cap band = y 2..22,
// baseline y = 22, wordmark starts at x ${fmt(WORD_X)}). See ./logo.ts for the spec.
`;
writeFileSync(
  'src/components/logo-wordmark.ts',
  `${header}
/** "Hayao" — ink. */
export const WORDMARK_HAYAO =
  "${HAYAO}";

/** ".js" — muted. */
export const WORDMARK_JS =
  "${JS}";

/** The full lockup's ink box (crown + wordmark, incl. j/y descenders). */
export const LOCKUP_VIEWBOX = "${viewBox}";

/** Lockup-unit metrics: cap band y 2..22; baseline y 22. */
export const LOCKUP_METRICS = {
  wordX: ${fmt(WORD_X)},
  wordWidth: ${fmt(TOTAL_ADVANCE * S)},
  right: ${fmt(right)},
  top: ${fmt(minY)},
  bottom: ${fmt(maxY)},
} as const;
`,
);

// Standalone assets — static colours (no CSS vars): for README, socials, embeds.
const CROWN = readFileSync('src/components/logo.ts', 'utf8').match(/LOGO_CROWN =\n  "([^"]+)"/)[1];
const RULE = readFileSync('src/components/logo.ts', 'utf8').match(/LOGO_RULE =\n  "([^"]+)"/)[1];
const svg = (ink, muted) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" role="img" aria-label="Hayao.js">
  <path d="${CROWN}" fill="#e59500"/>
  <path d="${RULE}" fill="${ink}"/>
  <path d="${HAYAO}" fill="${ink}"/>
  <path d="${JS}" fill="${muted}"/>
</svg>
`;
writeFileSync('public/logo.svg', svg('#29335c', '#8b90a6'));
writeFileSync('public/logo-dark.svg', svg('#eef1f9', '#727b9c'));

console.log(`ok — viewBox ${viewBox}, wordX ${fmt(WORD_X)}, paths ${HAYAO.length + JS.length} chars`);
