// Emits docs/API.md — the committed public-API digest. Fights hallucinated APIs:
// an agent greps ONE file for the real, current surface of '@hayao'. Run: npm run api

import ts from 'typescript';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const entry = resolve(root, 'src/index.ts');

const program = ts.createProgram([entry], {
  target: ts.ScriptTarget.ES2022,
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  strict: true,
  skipLibCheck: true,
});
const checker = program.getTypeChecker();
const source = program.getSourceFile(entry)!;
const moduleSymbol = checker.getSymbolAtLocation(source)!;
const exported = checker.getExportsOfModule(moduleSymbol);

interface Entry {
  name: string;
  kind: string;
  signature: string;
}

const flags = ts.SymbolFlags;
function classify(sym: ts.Symbol): string {
  const f = sym.getFlags();
  if (f & flags.Class) return 'class';
  if (f & flags.Interface) return 'interface';
  if (f & flags.TypeAlias) return 'type';
  if (f & flags.Enum) return 'enum';
  if (f & flags.Function) return 'function';
  if (f & flags.Variable) return 'const';
  if (f & flags.Property) return 'const';
  return 'export';
}

const entries: Entry[] = [];
for (const sym of exported) {
  const decl = sym.getDeclarations()?.[0];
  const type = decl ? checker.typeToString(checker.getTypeOfSymbolAtLocation(sym, decl)) : '';
  entries.push({ name: sym.getName(), kind: classify(sym), signature: type });
}
entries.sort((a, b) => a.kind.localeCompare(b.kind) || a.name.localeCompare(b.name));

const groups = new Map<string, Entry[]>();
for (const e of entries) {
  if (!groups.has(e.kind)) groups.set(e.kind, []);
  groups.get(e.kind)!.push(e);
}

let md = `# hayao.js — Public API digest\n\n`;
md += `> Auto-generated by \`npm run api\`. Everything importable from \`@hayao\`.\n`;
md += `> Grep here for the real surface — never guess an API from memory.\n\n`;
md += `**${entries.length} exports.**\n\n`;

const order = ['class', 'function', 'interface', 'type', 'const', 'enum', 'export'];
for (const kind of order) {
  const list = groups.get(kind);
  if (!list) continue;
  md += `## ${kind}s (${list.length})\n\n`;
  for (const e of list) {
    const sig = e.signature.length > 160 ? e.signature.slice(0, 157) + '…' : e.signature;
    md += `- \`${e.name}\`${kind === 'const' || kind === 'function' ? `: ${sig}` : ''}\n`;
  }
  md += '\n';
}

writeFileSync(resolve(root, 'docs/API.md'), md);
console.log(`Wrote docs/API.md — ${entries.length} exports.`);
