/**
 * THE canonical Hayao.js logo — single source of truth for the brand lockup.
 *
 * The mark: "Regalia" — an amber crown crossed by a navy rule, authored in a
 * tight "2 2 20 20" viewBox (the glyph fills the 20-unit square edge to edge,
 * so 1 rendered unit of height = 1 unit of glyph — it sizes true).
 *
 * The lockup is pure vector — the "Hayao.js" wordmark is OUTLINED from
 * Overpass 600 with real kerning (see ./logo-wordmark.ts, generated by
 * web/scripts/outline-logo.mjs), so the logo renders identically everywhere
 * with no font loading. Its geometry, in lockup units:
 *   - crown: x 2..22, cap band y 2..22 — cap height 20, foot ON the baseline
 *     at y = 22 (exactly a capital H's band; never taller, never centred)
 *   - wordmark: cap height 20 too, baseline y = 22, starts at x 32.39
 *     (gap = 0.36 em — gap-2 at the site's original 1.375rem lockup)
 *   - colors: crown #e59500 (Regalia orange — constant in both themes),
 *     rule + "Hayao" in ink (--color-ink, #29335c light / #eef1f9 dark),
 *     ".js" in muted (--color-muted)
 *
 * Render it via Logo.astro: `<Logo />` (mark only) or `<Logo wordmark />`
 * (the full lockup). Never re-set the wordmark in a live font.
 *
 * Consumers (keep these in sync — they cannot all import this module):
 *   - Logo.astro            — renders from these constants (mark or full lockup)
 *   - SiteNav.tsx           — imports these constants (React island)
 *   - pages/style.astro     — imports these constants (style-guide specimens)
 *   - public/logo.svg + logo-dark.svg — generated static assets (outline-logo.mjs)
 *   - public/favicon.svg    — verbatim copy of the mark (static asset)
 *   - src/app/splash.ts     — verbatim copy (engine boot cover; the engine
 *                             package cannot depend on web/)
 */
export { WORDMARK_HAYAO, WORDMARK_JS, LOCKUP_VIEWBOX, LOCKUP_METRICS } from "./logo-wordmark";

export const LOGO_VIEWBOX = "2 2 20 20";

export const LOGO_CROWN =
  "m21.8382 11.1263 -0.2292 2.4353c-0.3777 4.0126 -0.5665 6.0189 -1.7491 7.2286C18.6773 22 16.9048 22 13.3599 22h-2.7198c-3.54493 0 -5.31739 0 -6.50001 -1.2098 -1.18261 -1.2097 -1.37144 -3.216 -1.74909 -7.2286l-0.22919 -2.4353c-0.18001 -1.9126 -0.27001 -2.86891 0.05718 -3.26423 0.17699 -0.21384 0.41767 -0.34487 0.675 -0.36747 0.47569 -0.04178 1.07309 0.6383 2.26788 1.99847 0.6179 0.70343 0.92685 1.05513 1.2715 1.10963 0.19097 0.0301 0.38555 -0.0009 0.56189 -0.0896 0.31825 -0.1602 0.53044 -0.59498 0.95481 -1.46458l2.23683 -4.58366C10.9888 2.82162 11.3898 2 12 2c0.6102 0 1.0112 0.82162 1.8131 2.46485l2.2368 4.58366c0.4244 0.86961 0.6366 1.30439 0.9548 1.46459 0.1764 0.0887 0.371 0.1197 0.5619 0.0896 0.3447 -0.0545 0.6536 -0.4062 1.2715 -1.10963 1.1948 -1.36017 1.7922 -2.04025 2.2679 -1.99847 0.2573 0.0226 0.498 0.15363 0.675 0.36747 0.3272 0.39532 0.2372 1.35163 0.0572 3.26423Z";

export const LOGO_RULE =
  "M8.25 18c0 -0.4142 0.33579 -0.75 0.75 -0.75h6c0.4142 0 0.75 0.3358 0.75 0.75s-0.3358 0.75 -0.75 0.75H9c-0.41421 0 -0.75 -0.3358 -0.75 -0.75Z";

/** Crown gold — the one brand color that never changes with theme. */
export const LOGO_GOLD = "#e59500";
/** Static-context inks (contexts with no CSS vars, e.g. the favicon, emails). */
export const LOGO_INK_STATIC = "#29335c";
export const LOGO_MUTED_STATIC = "#8b90a6";

/**
 * The canonical on-site display size for the full lockup: cap height 15.4px —
 * what a 22px/600 Overpass wordmark measured before it was outlined. The
 * lockup viewBox is 26.66 units tall for a 20-unit cap, so 15.4 × 26.66/20.
 */
export const LOCKUP_CLASS = "h-[20.5px] w-auto";
